애널리틱스 이벤트 추가 (베타테스트 신청 버튼)
greatleee/poolda pull request #2
Opened 2020-04-22 05:41 UTC by ksong3838

2020-04-22 06:19 UTC, greatleee requested changes
@ksong3838

2020-04-22 06:19 UTC, greatleee commented on index.html
> +            <!--원문 <a href="https://forms.gle/CPPLabs9xRy44NSm7" class="download-btn">테스터 신청하기</a>-->
```suggestion
```

주석말고 그냥 지워주세요~

2020-04-22 06:28 UTC, ksong3838 commented
주석부분 지웠습니다.

2020-04-22 06:32 UTC, greatleee approved these changes

2020-04-22 06:33 UTC, greatleee commented
@ksong3838 "Merge pull request" 버튼 옆에 화살표 버튼을 누르면 3개 항목이 뜨는데 "squash ~"를 누르시면 이 PR(pull request) 제목으로 merge가 됩니다.

2020-04-22 06:45 UTC, ksong3838 commented
@greatleee 안내해 주신 방법대로 처리했습니다. 감사합니다.

2020-04-29 13:46 UTC, greatleee commented
#3 에서 처리됨

2020-04-29 13:46 UTC, closed without merging